import { CrosshairSettings } from '../types/types'

export const PRESETS: Record<string, CrosshairSettings> = {
  default: {
    color: '#00FF00',
    thickness: 2,
    length: 20,
    gap: 5,
    dot: false,
    opacity: 1,
    pipOpacity: 1,
    dotOutlineOpacity: 1,
    hitMarkerDuration: 0.1,
    pipBorder: false,
    pipGapStatic: false,
  },
  classic: {
    color: '#FFFFFF',
    thickness: 1,
    length: 8,
    gap: 2,
    dot: true,
    opacity: 1,
    pipOpacity: 1,
    dotOutlineOpacity: 1,
    hitMarkerDuration: 0.1,
    pipBorder: false,
    pipGapStatic: false,
  },
  tactical: {
    color: '#FF0000',
    thickness: 3,
    length: 15,
    gap: 8,
    dot: true,
    opacity: 0.8,
    pipOpacity: 0.8,
    dotOutlineOpacity: 0.8,
    hitMarkerDuration: 0.2,
    pipBorder: true,
    pipGapStatic: true,
  },
  minimal: {
    color: '#00FFFF',
    thickness: 1,
    length: 4,
    gap: 0,
    dot: true,
    opacity: 0.6,
    pipOpacity: 0.6,
    dotOutlineOpacity: 0.6,
    hitMarkerDuration: 0.1,
    pipBorder: false,
    pipGapStatic: false,
  },
} 