ALTER TABLE player_stats
ADD COLUMN player_rank INT NOT NULL DEFAULT 1000,
ADD COLUMN total_matches INT NOT NULL DEFAULT 0,
ADD COLUMN total_kills INT NOT NULL DEFAULT 0,
ADD COLUMN total_deaths INT NOT NULL DEFAULT 0,
ADD COLUMN total_assists INT NOT NULL DEFAULT 0; 