app:
  name: deadlock-stats
  version: 0.1.0
  client_url: http://localhost:3000

server:
  port: 8080
  timeout: 30s

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: deadlock_stats
  sslmode: disable
  max_connections: 20

redis:
  addr: "redis:6379"
  password: ""
  db: 0

steam:
  steam_api_key: 1234567890
  domain: http://localhost:8080

jwt:
  secret: "change-me-in-production"
  expiration: 24h 

api:
  timeout: 10s
  max_retries: 3
  connection_pool: 100
  idle_conn_timeout: 90s
  cache_ttl: 30m
  partial_cache_ttl: 1h
  enable_metrics: true
  enable_retry: true 