app:
  name: deadlock-stats
  version: 0.1.0

server:
  port: 8080
  timeout: 30s

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: deadlock_stats
  sslmode: disable
  max_connections: 20

redis:
  addr: "redis:6379"
  password: ""
  db: 0

steam:
  steam_api_key: 1234567890
  domain: http://localhost:8080

jwt:
  secret: "change-me-in-production"
  expiration: 24h 